#!/QOpenSys/pkgs/bin/bash

rm -rf ./logs/*
mkdir -p ./logs/prouzalib; \
mkdir -p ./logs/prouzalib2
mkdir -p ./build/prouzalib; \
mkdir -p ./build/prouzalib2
(	cl "CHGATR OBJ('"'prouzalib//qsqlsrc/logger.sqltable'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "RUNSQLSTM SRCSTMF('./prouzalib//qsqlsrc/"logger".sqltable') DFTRDBCOL(T1) COMMIT(*NONE) ERRLVL(21)"    2>> './logs/prouzalib/logger.sqltable.file.error.log'  >> './logs/prouzalib/logger.sqltable.file.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/logger.sqltable.file.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/logger.sqltable.file.error.log' > './logs/prouzalib/logger.sqltable.file.error.log'_tmp && mv './logs/prouzalib/logger.sqltable.file.error.log'_tmp './logs/prouzalib/logger.sqltable.file.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/logger.sqltable.file.splf.log' > './logs/prouzalib/logger.sqltable.file.splf.log'_tmp && mv './logs/prouzalib/logger.sqltable.file.splf.log'_tmp './logs/prouzalib/logger.sqltable.file.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/logger.sqltable.file.joblog.log' > './logs/prouzalib/logger.sqltable.file.joblog.log'_tmp && mv './logs/prouzalib/logger.sqltable.file.joblog.log'_tmp './logs/prouzalib/logger.sqltable.file.joblog.log'  ; if [ -s './logs/prouzalib/logger.sqltable.file.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qsqlsrc/logger.sqltable\033[0m' 1>&2
exit
fi && touch './build/prouzalib/logger.sqltable.file'
(	cl "CHGATR OBJ('"'prouzalib//qrpglesrc/logger.sqlrpgle'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "CRTSQLRPGI OBJ("T1/logger") SRCSTMF('./prouzalib//qrpglesrc/"logger".sqlrpgle') OBJTYPE(*MODULE) RPGPPOPT(*LVL2) TGTRLS(*CURRENT) DBGVIEW(*SOURCE) REPLACE(*YES) COMPILEOPT('TGTCCSID(*JOB) INCDIR(''./prouzalib/'')')"    2>> './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/logger.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/logger.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  -q "RMVBNDDIRE BNDDIR(*LIBL/PROUZADIR) OBJ("*LIBL/logger")"   2>> './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/logger.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/logger.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  "CRTSRVPGM SRVPGM("T1/logger") MODULE("T1/logger") EXPORT(*ALL) ACTGRP(PROUZAGRP) BNDDIR(*LIBL/PROUZADIR) REPLACE(*YES) TGTRLS(*CURRENT) STGMDL(*SNGLVL)"    2>> './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/logger.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/logger.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  "ADDBNDDIRE BNDDIR(*LIBL/PROUZADIR) OBJ("*LIBL/logger")"   2>> './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/logger.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/logger.sqlrpgle.srvpgm.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log' > './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log'_tmp && mv './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log'_tmp './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/logger.sqlrpgle.srvpgm.splf.log' > './logs/prouzalib/logger.sqlrpgle.srvpgm.splf.log'_tmp && mv './logs/prouzalib/logger.sqlrpgle.srvpgm.splf.log'_tmp './logs/prouzalib/logger.sqlrpgle.srvpgm.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/logger.sqlrpgle.srvpgm.joblog.log' > './logs/prouzalib/logger.sqlrpgle.srvpgm.joblog.log'_tmp && mv './logs/prouzalib/logger.sqlrpgle.srvpgm.joblog.log'_tmp './logs/prouzalib/logger.sqlrpgle.srvpgm.joblog.log'  ; if [ -s './logs/prouzalib/logger.sqlrpgle.srvpgm.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qrpglesrc/logger.sqlrpgle\033[0m' 1>&2
exit
fi && touch './build/prouzalib/logger.sqlrpgle.srvpgm'
(	cl "CHGATR OBJ('"'prouzalib//qrpglesrc/errhdlsql.sqlrpgle'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "CRTSQLRPGI OBJ("T1/errhdlsql") SRCSTMF('./prouzalib//qrpglesrc/"errhdlsql".sqlrpgle') OBJTYPE(*MODULE) RPGPPOPT(*LVL2) TGTRLS(*CURRENT) DBGVIEW(*SOURCE) REPLACE(*YES) COMPILEOPT('TGTCCSID(*JOB) INCDIR(''./prouzalib/'')')"    2>> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  -q "RMVBNDDIRE BNDDIR(*LIBL/PROUZADIR) OBJ("*LIBL/errhdlsql")"   2>> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  "CRTSRVPGM SRVPGM("T1/errhdlsql") MODULE("T1/errhdlsql") EXPORT(*ALL) ACTGRP(PROUZAGRP) BNDDIR(*LIBL/PROUZADIR) REPLACE(*YES) TGTRLS(*CURRENT) STGMDL(*SNGLVL)"    2>> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  "ADDBNDDIRE BNDDIR(*LIBL/PROUZADIR) OBJ("*LIBL/errhdlsql")"   2>> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log' > './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log'_tmp && mv './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log'_tmp './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.splf.log' > './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.splf.log'_tmp && mv './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.splf.log'_tmp './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.joblog.log' > './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.joblog.log'_tmp && mv './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.joblog.log'_tmp './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.joblog.log'  ; if [ -s './logs/prouzalib/errhdlsql.sqlrpgle.srvpgm.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qrpglesrc/errhdlsql.sqlrpgle\033[0m' 1>&2
exit
fi && touch './build/prouzalib/errhdlsql.sqlrpgle.srvpgm'
(	cl "CHGATR OBJ('"'prouzalib//qrpglesrc/cpysrc2ifs.sqlrpgle'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "CRTSQLRPGI OBJ("T1/cpysrc2ifs") SRCSTMF('./prouzalib//qrpglesrc/"cpysrc2ifs".sqlrpgle') OBJTYPE(*MODULE) RPGPPOPT(*LVL2) TGTRLS(*CURRENT) DBGVIEW(*SOURCE) REPLACE(*YES) COMPILEOPT('TGTCCSID(*JOB) INCDIR(''./prouzalib/'')')"    2>> './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.error.log'  >> './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.joblog.log')
( cl  -v  "CRTPGM PGM("T1/cpysrc2ifs") ACTGRP(PROUZAGRP) REPLACE(*YES) TGTRLS(*CURRENT) STGMDL(*SNGLVL) DETAIL(*BASIC) BNDDIR(*LIBL/PROUZADIR)"    2>> './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.error.log'  >> './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.error.log' > './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.error.log'_tmp && mv './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.error.log'_tmp './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.splf.log' > './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.splf.log'_tmp && mv './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.splf.log'_tmp './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.joblog.log' > './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.joblog.log'_tmp && mv './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.joblog.log'_tmp './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.joblog.log'  ; if [ -s './logs/prouzalib/cpysrc2ifs.sqlrpgle.pgm.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qrpglesrc/cpysrc2ifs.sqlrpgle\033[0m' 1>&2
exit
fi && touch './build/prouzalib/cpysrc2ifs.sqlrpgle.pgm'
(	cl "CHGATR OBJ('"'prouzalib//qrpglesrc/date.sqlrpgle'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "CRTSQLRPGI OBJ("T1/date") SRCSTMF('./prouzalib//qrpglesrc/"date".sqlrpgle') OBJTYPE(*MODULE) RPGPPOPT(*LVL2) TGTRLS(*CURRENT) DBGVIEW(*SOURCE) REPLACE(*YES) COMPILEOPT('TGTCCSID(*JOB) INCDIR(''./prouzalib/'')')"    2>> './logs/prouzalib/date.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/date.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/date.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  -q "RMVBNDDIRE BNDDIR(*LIBL/PROUZADIR) OBJ("*LIBL/date")"   2>> './logs/prouzalib/date.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/date.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/date.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  "CRTSRVPGM SRVPGM("T1/date") MODULE("T1/date") EXPORT(*ALL) ACTGRP(PROUZAGRP) BNDDIR(*LIBL/PROUZADIR) REPLACE(*YES) TGTRLS(*CURRENT) STGMDL(*SNGLVL)"    2>> './logs/prouzalib/date.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/date.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/date.sqlrpgle.srvpgm.joblog.log')
(  cl  -v  "ADDBNDDIRE BNDDIR(*LIBL/PROUZADIR) OBJ("*LIBL/date")"   2>> './logs/prouzalib/date.sqlrpgle.srvpgm.error.log'  >> './logs/prouzalib/date.sqlrpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/date.sqlrpgle.srvpgm.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/date.sqlrpgle.srvpgm.error.log' > './logs/prouzalib/date.sqlrpgle.srvpgm.error.log'_tmp && mv './logs/prouzalib/date.sqlrpgle.srvpgm.error.log'_tmp './logs/prouzalib/date.sqlrpgle.srvpgm.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/date.sqlrpgle.srvpgm.splf.log' > './logs/prouzalib/date.sqlrpgle.srvpgm.splf.log'_tmp && mv './logs/prouzalib/date.sqlrpgle.srvpgm.splf.log'_tmp './logs/prouzalib/date.sqlrpgle.srvpgm.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/date.sqlrpgle.srvpgm.joblog.log' > './logs/prouzalib/date.sqlrpgle.srvpgm.joblog.log'_tmp && mv './logs/prouzalib/date.sqlrpgle.srvpgm.joblog.log'_tmp './logs/prouzalib/date.sqlrpgle.srvpgm.joblog.log'  ; if [ -s './logs/prouzalib/date.sqlrpgle.srvpgm.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qrpglesrc/date.sqlrpgle\033[0m' 1>&2
exit
fi && touch './build/prouzalib/date.sqlrpgle.srvpgm'
(	cl "CHGATR OBJ('"'prouzalib//qrpglesrc/testmod.rpgle'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "CRTRPGMOD MODULE("T1/testmod") SRCSTMF('./prouzalib//qrpglesrc/"testmod".rpgle') DBGVIEW(*SOURCE) REPLACE(*YES) TGTCCSID(*JOB) INCDIR('./prouzalib/')"    2>> './logs/prouzalib/testmod.rpgle.srvpgm.error.log'  >> './logs/prouzalib/testmod.rpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testmod.rpgle.srvpgm.joblog.log')
(  cl  -v  -q "RMVBNDDIRE BNDDIR(*LIBL/PROUZADIR) OBJ("*LIBL/testmod")"   2>> './logs/prouzalib/testmod.rpgle.srvpgm.error.log'  >> './logs/prouzalib/testmod.rpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testmod.rpgle.srvpgm.joblog.log')
(  cl  -v  "CRTSRVPGM SRVPGM("T1/testmod") MODULE("T1/testmod") EXPORT(*ALL) ACTGRP(PROUZAGRP) BNDDIR(*LIBL/PROUZADIR) REPLACE(*YES) TGTRLS(*CURRENT) STGMDL(*SNGLVL)"    2>> './logs/prouzalib/testmod.rpgle.srvpgm.error.log'  >> './logs/prouzalib/testmod.rpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testmod.rpgle.srvpgm.joblog.log')
(  cl  -v  "ADDBNDDIRE BNDDIR(*LIBL/PROUZADIR) OBJ("*LIBL/testmod")"   2>> './logs/prouzalib/testmod.rpgle.srvpgm.error.log'  >> './logs/prouzalib/testmod.rpgle.srvpgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testmod.rpgle.srvpgm.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testmod.rpgle.srvpgm.error.log' > './logs/prouzalib/testmod.rpgle.srvpgm.error.log'_tmp && mv './logs/prouzalib/testmod.rpgle.srvpgm.error.log'_tmp './logs/prouzalib/testmod.rpgle.srvpgm.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testmod.rpgle.srvpgm.splf.log' > './logs/prouzalib/testmod.rpgle.srvpgm.splf.log'_tmp && mv './logs/prouzalib/testmod.rpgle.srvpgm.splf.log'_tmp './logs/prouzalib/testmod.rpgle.srvpgm.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testmod.rpgle.srvpgm.joblog.log' > './logs/prouzalib/testmod.rpgle.srvpgm.joblog.log'_tmp && mv './logs/prouzalib/testmod.rpgle.srvpgm.joblog.log'_tmp './logs/prouzalib/testmod.rpgle.srvpgm.joblog.log'  ; if [ -s './logs/prouzalib/testmod.rpgle.srvpgm.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qrpglesrc/testmod.rpgle\033[0m' 1>&2
exit
fi && touch './build/prouzalib/testmod.rpgle.srvpgm'
touch ./build/prouzalib/prouzadir.bnddir
(	cl "CHGATR OBJ('"'prouzalib//qrpglesrc/testlog.rpgle'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "CRTRPGMOD MODULE("T3/testlog") SRCSTMF('./prouzalib//qrpglesrc/"testlog".rpgle') DBGVIEW(*SOURCE) REPLACE(*YES) TGTCCSID(*JOB) INCDIR('./prouzalib/')"    2>> './logs/prouzalib/testlog.rpgle.pgm.error.log'  >> './logs/prouzalib/testlog.rpgle.pgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testlog.rpgle.pgm.joblog.log')
( cl  -v  "CRTPGM PGM("T3/testlog") ACTGRP(PROUZAGRP) REPLACE(*YES) TGTRLS(*CURRENT) STGMDL(*SNGLVL) DETAIL(*BASIC) BNDDIR(*LIBL/PROUZADIR)"    2>> './logs/prouzalib/testlog.rpgle.pgm.error.log'  >> './logs/prouzalib/testlog.rpgle.pgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testlog.rpgle.pgm.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testlog.rpgle.pgm.error.log' > './logs/prouzalib/testlog.rpgle.pgm.error.log'_tmp && mv './logs/prouzalib/testlog.rpgle.pgm.error.log'_tmp './logs/prouzalib/testlog.rpgle.pgm.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testlog.rpgle.pgm.splf.log' > './logs/prouzalib/testlog.rpgle.pgm.splf.log'_tmp && mv './logs/prouzalib/testlog.rpgle.pgm.splf.log'_tmp './logs/prouzalib/testlog.rpgle.pgm.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testlog.rpgle.pgm.joblog.log' > './logs/prouzalib/testlog.rpgle.pgm.joblog.log'_tmp && mv './logs/prouzalib/testlog.rpgle.pgm.joblog.log'_tmp './logs/prouzalib/testlog.rpgle.pgm.joblog.log'  ; if [ -s './logs/prouzalib/testlog.rpgle.pgm.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qrpglesrc/testlog.rpgle\033[0m' 1>&2
exit
fi && touch './build/prouzalib/testlog.rpgle.pgm'
(	cl "CHGATR OBJ('"'prouzalib//qrpglesrc/testlog2.sqlrpgle'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "CRTSQLRPGI OBJ("T1/testlog2") SRCSTMF('./prouzalib//qrpglesrc/"testlog2".sqlrpgle') OBJTYPE(*MODULE) RPGPPOPT(*LVL2) TGTRLS(*CURRENT) DBGVIEW(*SOURCE) REPLACE(*YES) COMPILEOPT('TGTCCSID(*JOB) INCDIR(''./prouzalib/'')')"    2>> './logs/prouzalib/testlog2.sqlrpgle.pgm.error.log'  >> './logs/prouzalib/testlog2.sqlrpgle.pgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testlog2.sqlrpgle.pgm.joblog.log')
( cl  -v  "CRTPGM PGM("T1/testlog2") ACTGRP(PROUZAGRP) REPLACE(*YES) TGTRLS(*CURRENT) STGMDL(*SNGLVL) DETAIL(*BASIC) BNDDIR(*LIBL/PROUZADIR)"    2>> './logs/prouzalib/testlog2.sqlrpgle.pgm.error.log'  >> './logs/prouzalib/testlog2.sqlrpgle.pgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testlog2.sqlrpgle.pgm.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testlog2.sqlrpgle.pgm.error.log' > './logs/prouzalib/testlog2.sqlrpgle.pgm.error.log'_tmp && mv './logs/prouzalib/testlog2.sqlrpgle.pgm.error.log'_tmp './logs/prouzalib/testlog2.sqlrpgle.pgm.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testlog2.sqlrpgle.pgm.splf.log' > './logs/prouzalib/testlog2.sqlrpgle.pgm.splf.log'_tmp && mv './logs/prouzalib/testlog2.sqlrpgle.pgm.splf.log'_tmp './logs/prouzalib/testlog2.sqlrpgle.pgm.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testlog2.sqlrpgle.pgm.joblog.log' > './logs/prouzalib/testlog2.sqlrpgle.pgm.joblog.log'_tmp && mv './logs/prouzalib/testlog2.sqlrpgle.pgm.joblog.log'_tmp './logs/prouzalib/testlog2.sqlrpgle.pgm.joblog.log'  ; if [ -s './logs/prouzalib/testlog2.sqlrpgle.pgm.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qrpglesrc/testlog2.sqlrpgle\033[0m' 1>&2
exit
fi && touch './build/prouzalib/testlog2.sqlrpgle.pgm'
(	cl "CHGATR OBJ('"'prouzalib//qrpglesrc/testsqlerr.sqlrpgle'"') ATR(*CCSID) VALUE(1208)" | iconv -f IBM-1252 -t utf-8 
)
( cl  -v  "CRTSQLRPGI OBJ("T1/testsqlerr") SRCSTMF('./prouzalib//qrpglesrc/"testsqlerr".sqlrpgle') OBJTYPE(*MODULE) RPGPPOPT(*LVL2) TGTRLS(*CURRENT) DBGVIEW(*SOURCE) REPLACE(*YES) COMPILEOPT('TGTCCSID(*JOB) INCDIR(''./prouzalib/'')')"    2>> './logs/prouzalib/testsqlerr.sqlrpgle.pgm.error.log'  >> './logs/prouzalib/testsqlerr.sqlrpgle.pgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testsqlerr.sqlrpgle.pgm.joblog.log')
( cl  -v  "CRTPGM PGM("T1/testsqlerr") ACTGRP(PROUZAGRP) REPLACE(*YES) TGTRLS(*CURRENT) STGMDL(*SNGLVL) DETAIL(*BASIC) BNDDIR(*LIBL/PROUZADIR)"    2>> './logs/prouzalib/testsqlerr.sqlrpgle.pgm.error.log'  >> './logs/prouzalib/testsqlerr.sqlrpgle.pgm.splf.log' ; cl -v  "DSPJOBLOG" >> './logs/prouzalib/testsqlerr.sqlrpgle.pgm.joblog.log')
iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testsqlerr.sqlrpgle.pgm.error.log' > './logs/prouzalib/testsqlerr.sqlrpgle.pgm.error.log'_tmp && mv './logs/prouzalib/testsqlerr.sqlrpgle.pgm.error.log'_tmp './logs/prouzalib/testsqlerr.sqlrpgle.pgm.error.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testsqlerr.sqlrpgle.pgm.splf.log' > './logs/prouzalib/testsqlerr.sqlrpgle.pgm.splf.log'_tmp && mv './logs/prouzalib/testsqlerr.sqlrpgle.pgm.splf.log'_tmp './logs/prouzalib/testsqlerr.sqlrpgle.pgm.splf.log'  ; iconv -f IBM-1252 -t utf-8 './logs/prouzalib/testsqlerr.sqlrpgle.pgm.joblog.log' > './logs/prouzalib/testsqlerr.sqlrpgle.pgm.joblog.log'_tmp && mv './logs/prouzalib/testsqlerr.sqlrpgle.pgm.joblog.log'_tmp './logs/prouzalib/testsqlerr.sqlrpgle.pgm.joblog.log'  ; if [ -s './logs/prouzalib/testsqlerr.sqlrpgle.pgm.error.log' ]; then
echo -e '\033[101;31mfailed: prouzalib//qrpglesrc/testsqlerr.sqlrpgle\033[0m' 1>&2
exit
fi && touch './build/prouzalib/testsqlerr.sqlrpgle.pgm'
cat ./logs/*.error.log 2> /dev/null | true
echo -e "\033[102;97mCompile complete\033[0m"
